version: '3.9'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=production
      - DB_HOST=mariadb
      - DB_USER=root
      - DB_PASS=${DB_PASSWORD}
    depends_on:
      - mariadb
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  mariadb:
    image: mariadb:11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mariadb-data:/var/lib/mysql

volumes:
  mariadb-data:
