-- =========================================================
-- Esquema: datos_maestros
-- Tabla: cat_sociedades
-- Archivo: 02_constraints.sql
-- =========================================================
