-- =========================================================
-- Esquema: datos_maestros
-- Tabla: cat_centrales_generacion
-- =========================================================
drop table if exists datos_maestros.cat_centrales_generacion cascade;
create table datos_maestros.cat_centrales_generacion (
    id_central_generacion bigint generated by default as identity not null,
    nombre_central text not null,
    ubicacion_estado text not null,
    ubicacion_municipio text null,
    tipo_central text not null,
    estado_operacion text not null,
    capacidad_mw numeric null,
    combustible_principal text null,
    combustible_secundario text null,
    created_at timestamp null default (now() at time zone 'America/Monterrey'),
    updated_at timestamp null default (now() at time zone 'America/Monterrey'),
    constraint centrales_pkey primary key (id_central_generacion),
    constraint uq_nombre_central unique (nombre_central)
) TABLESPACE pg_default;
-- =========================================================
-- ÍNDICES
create index if not exists idx_centrales_estado on datos_maestros.cat_centrales_generacion (ubicacion_estado);
create index if not exists idx_centrales_tipo on datos_maestros.cat_centrales_generacion (tipo_central);
create index if not exists idx_centrales_nombre_normalizado on datos_maestros.cat_centrales_generacion (lower(trim(nombre_central)));
-- =========================================================
-- TRIGGERS
-- =========================================================
create trigger trg_set_updated_at_mx_centrales_generacion before
update on datos_maestros.cat_centrales_generacion for each row execute function public.set_updated_at_mx();
