-- ======================================================================
-- DEPRECATED WRAPPER
-- La orquestacion vive en etl.pr_load_precios_vinculantes_combustibles()
-- ======================================================================
