truncate table staging.stg_precios_vinculantes_combustibles;

drop table if exists staging.precios_vinculantes_combustibles_normalized;
drop table if exists staging.precios_vinculantes_combustibles_ready;
